### ISSUE TITLE
Feature: Rework Docker support

### ISSUE THREAD

**Issue by krumware** [calcom/docker#102]
Discussed with @zomars & @PeerRich

We are going to:

 - Rework submodule requirements
 - Add npm credentials and help with calcom package inclusion
 - Do Not Include enterprise API in public image
 - Formalize helm and docker support, including documentation

**Comment by finaldzn** [comment]
For the helm part, I've submitted my PR. We have been using the chart with no issues so far

**Comment by krumware** [comment]
👍 definitely on track there
