### ISSUE TITLE
Build failed: JavaScript heap out of memory

### ISSUE THREAD

**Issue by devinellis** [calcom/docker#115]
I'm excited to try out cal.com. I had to upgrade the VM up to 8GB for the build to complete, which seems like a lot for a webapp (the build was the only thing running). Maybe down the road, a pre-compiled build of the app could be distributed via docker? It was also is unfortunate that I had to completely rebuild when I changed NEXT_PUBLIC_WEBAPP_URL to a public URL, vs having it as an environment variable that just requires a recreate.

```
#0 384.6 @calcom/web:build: FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
```

**Comment by krumware** [comment]
We've brought the team's attention to the static site built restrictions in the past, so I know it's on their radar, but I'm not certain of current status (definitely please open up an issue in the calcom repo and voice your feedback!). This is hotly debated topic in the self-hosting vs saas space.

Just adding some context:
- The NEXT_PUBLIC_WEBAPP_URL could be moved to runtime variables, but the team's focus on site speed has indicated that the way the url is embedded in anchors in the pages, that it would cause a number of pages to lose their static capabilities.
- We could move the static build to runtime to compensate, but the container would then require more memory as well and would have a drastically slower time-to-liveness.
- There is a way to hint to the javascript NODE_OPTIONS="--max-old-space-size=4096"

You could try adding that last option to the dockerfile and see if it helps you? you can play with the value

```
ENV NEXT_PUBLIC_WEBAPP_URL=$NEXT_PUBLIC_WEBAPP_URL \
    NEXT_PUBLIC_APP_URL=$NEXT_PUBLIC_APP_URL \
    NEXT_PUBLIC_LICENSE_CONSENT=$NEXT_PUBLIC_LICENSE_CONSENT \
    NEXT_PUBLIC_TELEMETRY_KEY=$NEXT_PUBLIC_TELEMETRY_KEY \
    DATABASE_URL=$DATABASE_URL \
    NODE_OPTIONS=--max-old-space-size=4096
```

**Comment by krumware** [comment]
@devinellis Were you able to try changing the dockerfile to help with the memory issue?

**Comment by devinellis** [comment]
Since I have it up-and-running now, I haven't bothered to go back and rebuild. "If it ain't broke, don't fix it!" But I assume whenever I go to do an upgrade I'll try this out.

**Comment by krumware** [comment]
Sounds great! I'm going to go ahead and close this but please update this when you try again
