### ISSUE TITLE
How to update a docker-built container?

### ISSUE THREAD

**Issue by drwb** [calcom/docker#120]
What are the steps to update a previously built docker container?

I’d imagine an update of the repository
`git pull origin master ` ?

a (manual?) review of .env changes?

then somehow updating the database without losing data? perhaps there’s a new schema. this is where I’m conceptually stuck.

I also notice that the docs require the database to be run first, which my existing installation logs suggest is new?

then `docker build`?

**Comment by krumware** [comment]
tagging @zomars here. Since the schema update during compilation is very recent, there may be relevant steps for even the non-container build that are documented and can be adapted

**Comment by krumware** [comment]
But the Prisma migrations in the build are safe for existing databases, correct? Wasn't sure if there were any recommendations for upgrading in production and running the build against a shadow db

**Comment by zomars** [comment]
They should be safe yes
