### ISSUE TITLE
Google configuration 

### ISSUE THREAD

**Issue by siddjellali** [calcom/docker#133]
Hi, 

How can we confirm google calendar ?
Google are installed but not configured ...

![image](https://user-images.githubusercontent.com/3965823/174811851-10eed4f8-e2e0-46df-b40b-7d8b7eea2963.png)

https://github.com/calcom/docker/issues/126
Thanks !

**Comment by krumware** [comment]
I can confirm that it is working, at least when passing the variables into the env of the machine.
Do you have the google credentials added in your runtime env variables?

**Comment by siddjellali** [comment]
Yes all seems good but as display in capture above ... no setting available.
For info, env.appStore is located on /var/lib/postgresql/data/ directory

**Comment by krumware** [comment]
Is there anything you can share in the way of build or startup logs that would give more insight?
Otherwise I'm flying blind on your specific configuration.

The env.appStore is referenced by the seed script via relative path needs to be located in the calcom folder. Could your file location be the issue?
![image](https://user-images.githubusercontent.com/17303782/175338260-bb8560a0-7d2d-4bb6-8550-30638324dbfd.png)

**Comment by siddjellali** [comment]
Something wrong on the new docker release, i guess.

After a new install, all application in the store is "Cal Video"
![image](https://user-images.githubusercontent.com/3965823/175517454-baa8b9a5-66f8-47fe-8d70-48f841a749cc.png)

**Comment by krumware** [comment]
@siddjellali this looks like it is cal.com project related and not necessarily specific to the docker build. Can you by chance open another issue on that side and link to this one for context?

**Comment by siddjellali** [comment]
@krumware docker image seems not fully operationnal. 
For instance, the calcom code is not up to date.

<img width="1220" alt="Capture d’écran 2022-06-27 à 15 07 15" src="https://user-images.githubusercontent.com/3965823/175948985-5048d446-a512-450a-86db-dccaf247fc1e.png">

**Comment by krumware** [comment]
are you using a self-built image or the dockerhub image?

are you referring to the "Update Available" text above or the WARN events?

**Comment by siddjellali** [comment]
Dockerhub image.
Yes i'm refering to this information "Update available".

**Comment by krumware** [comment]
![image](https://user-images.githubusercontent.com/17303782/176487394-1ab29356-fb70-407f-a219-c934fb930a33.png)

what method to set this up are you using?
- pulling the image and running directly?
- using this repository for building and pushing your own image?

and also how are you updating?

**Comment by siddjellali** [comment]
weird ... i have cleaned the cache and now i'm in 1.7.4
App store is well now but google setting is still now here...

![image](https://user-images.githubusercontent.com/3965823/176604447-fdd0ce18-ab56-47ed-a6ca-2eba86727810.png)

![image](https://user-images.githubusercontent.com/3965823/176604482-c1970508-aa26-48af-92d4-b8f272840cf3.png)

**Comment by siddjellali** [comment]
I did a fresh install...

**Comment by PeerRich** [comment]
did it work?

**Comment by siddjellali** [comment]
yes it did ! 
Same file / same configuration; basically, i just wipe the database.
