### ISSUE TITLE
error in default compose file

### ISSUE THREAD

**Issue by mokkin** [calcom/docker#137]
happens since this change https://github.com/calcom/docker/commit/c283a92614b54319a402207dd5de4e3e98751931
```
ERROR: The Compose file './docker-compose.yaml' is invalid because:
services.studio.profiles contains an invalid type, it should be an array
services.studio.volumes contains an invalid type, it should be an array

```

**Comment by krumware** [comment]
@kelvinalfaro this was introduced in your last commit. Are you able to address this?

**Comment by klipitkas** [comment]
This is still broken, any chance of fixing it?

**Comment by jschulman** [comment]
I'm getting:

services.studio.volumes must be a list

**Comment by agustif** [comment]
I think you guys are on docker-compose v2 and need to update to v3, or something similar. @jschulman @klipitkas can you try and let us know? Thank you

**Comment by krumware** [comment]
Was waiting for @kelvinalfaro but I'll jump on this today if still unresponsive

**Comment by jschulman** [comment]
> I think you guys are on docker-compose v2 and need to update to v3, or something similar. @jschulman @klipitkas can you try and let us know? Thank you

I'm running Docker version 20.10.17, build 100c701 with the latest docker-compose plugin.

What's weird is the DOCKER_BUILDKIT=0 isn't working.  Even tried exporting it as a global var and still get the:

network mode "stack" not supported by buildkit

**Comment by klipitkas** [comment]
Indeed I am using docker compose v2:

```
$ docker compose version 
Docker Compose version v2.6.1
```

I have patched the yaml file for now to make it work, attaching my patched version below that kind of works for me:
```
version: '3.1'

volumes:
  database-data:
  db-data:

networks:
  stack:
    name: stack
    external: false

services:
  database:
    image: postgres # profiles: ["withpostgres"] only starts when specifying this profile
    restart: unless-stopped
    volumes:
      - database-data:/var/lib/postgresql/data/
    env_file: .env
    networks:
      - stack
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  calcom:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_WEBAPP_URL=${NEXT_PUBLIC_WEBAPP_URL}
        - NEXT_PUBLIC_LICENSE_CONSENT=${NEXT_PUBLIC_LICENSE_CONSENT}
        - CALCOM_TELEMETRY_DISABLED=${CALCOM_TELEMETRY_DISABLED}
        - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
        - CALENDSO_ENCRYPTION_KEY=${CALENDSO_ENCRYPTION_KEY}
        - DATABASE_URL=${DATABASE_URL}
      network: stack
    restart: always
    networks:
      - stack
    ports:
      - ${PORT-3000}:3000
    env_file: .env
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NODE_ENV=development
      - POSTGRES_PASSWORD = ""
      - POSTGRES_HOST_AUTH_METHOD = trust
    depends_on:
      database: # comment out when using non-docker database (=enabled "withpostgres" profile)
        condition: service_healthy
    volumes:
      - "./calendso:/app/"
      - "./scripts:/app/scripts"

# Optional use of Prisma Studio. To use *with* Prisma Studio:
# docker-compose --profile withstudio up
  studio:
    image: calendso/calendso:latest
    container_name: calendso-studio
    restart: unless-stopped
    profiles: ["withstudio"] # only starts when specifying this profile
    networks:
      - stack
    ports:
      - 5555:5555
    volumes:
      - db_data
    env_file: .env
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      database: # comment out when using non-docker database (=enabled "withpostgres" profile)
        condition: service_healthy
    command:
      - npx
      - prisma
      - studio
```

I also have the database connection issue when building the calcom image so I guess this might be related to docker compose v2 as well.

**Comment by krumware** [comment]
We just reverted the previous changes via #139

This may sound redundant, but on the network issue, can you confirm for me that you are running `docker compose up -d database` prior to the build step?

**Comment by jschulman** [comment]
Just checked and it's still running:

57adabe5e154   postgres                          "docker-entrypoint.s…"   17 hours ago   Up 17 hours           5432/tcp                                                                                                   calendso-db

**Comment by klipitkas** [comment]
Yes me too, my postgres is still running from the morning when I tried to last build it:
```
CONTAINER ID   IMAGE      COMMAND                  CREATED        STATUS                  PORTS      NAMES
947776dd00a9   postgres   "docker-entrypoint.s…"   11 hours ago   Up 11 hours (healthy)   5432/tcp   calcom-docker-database-1
```

**Comment by wzrdtales** [comment]
when using up --force-recreate that solves. but

```
@calcom/prisma:db-deploy: Error: P1001: Can't reach database server at `db`:`5432`
@calcom/prisma:db-deploy: 
@calcom/prisma:db-deploy: Please make sure your database server is running at `db`:`5432`.
@calcom/prisma:db-deploy: error Command failed with exit code 1.
@calcom/prisma:db-deploy: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
@calcom/prisma:db-deploy: error Command failed with exit code 1.
@calcom/prisma:db-deploy: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
@calcom/prisma:db-deploy: ERROR: command finished with error: command (packages/prisma) yarn run db-deploy exited (1)
```

the build is broken in more than one way

**Comment by krumware** [comment]
The above can be addressed in a new issue. Need to see details related to potential changes in the docker-compose file, as the default network address for the database container is `database` not `db` as indicated by the log.

Closing this as the original issue in this thread is resolved
