### ISSUE TITLE
Submodule sync silently failing due to review requirement

### ISSUE THREAD

**Issue by ianonavy** [calcom/docker#167]
As of July 2022, calcom/docker has a branch protection rule on `main` that requires at least one review before merging. This revealed two bugs:
1. the submodule sync workflow stopped working
2. the submodule sync workflow reports a successful job even though it failed

The last step in the Actions workflow for submodule update ends with `|| echo`. Because `echo` always exit 0, GitHub Actions erroneously believes the job succeeded regardless of whether `git push` failed due to lack of new commits or failure to push. See [example](https://github.com/calcom/docker/actions/runs/3125121534/jobs/5069171258#step:4:12). This has been failing since 1.7.6 [cal.com@6b0ac9](https://github.com/calcom/cal.com/tree/6b0ac96b38b0dbd78809a73e19010192f31cc769).

Instead of committing and pushing on one line, I would recommend separating the check for new commits to its own line. That way, you can do an early `exit(0)` if there are no new commits, and correctly fail the job if `git push` errors out.

To fix the issue with the branch protection rule, there are a few options. In no particular order:

1. Remove the PR requirement.
3. Create a [GitHub app as an exception to the branch protection rule](https://github.blog/changelog/2022-05-17-consistently-allow-github-apps-as-exceptions-to-branch-protection-rules/) (seems complicated, but as of today [actions-user cannot be added to the exception list](https://github.com/community/community/discussions/13836)).
4. Change the sync script to submit a PR instead.
5. Instead of using a submodule, just do a `git clone` in the docker build and push workflow.

**Comment by krumware** [comment]
Thanks for calling this out! I'll look into it

**Comment by krumware** [comment]
I temporarily alleviated the protection requirements in the mean time while we sort that out. Also manually triggered the update/build/push

**Comment by ianonavy** [comment]
Awesome! Looks like that temporary fix is working. Looking forward to the permanent fix.
