### ISSUE TITLE
Run database and calcom in one container

### ISSUE THREAD

**Issue by Septa2112** [calcom/docker#184]
Hello, I'm trying to run the database and calcom in one container. 
Is this feasible? Or any suggestions for this? Thanks!

**Comment by krumware** [comment]
I wouldn't recommend trynig to merge the two together. You could run them together in the same Pod if you needed to, but you're effectively doing the same thing when you run both containers on the same host machine.

**Comment by Septa2112** [comment]
Thanks for your suggestions! 
That is because I want to do some benchmark testing on calcom. But I don't want the test result to be affected by network connection between two dockers.
Now I successfully installed postgresql in calcom/docker and the merged-container runs well.

But there is a problem that I can't enter the login interface. Whenever I try to enter localhost:3000, the page automatically jumps to localhost:3000/event-types. Just like this. Any suggestions for me? Thanks.

![屏幕截图 2022-12-16 123315](https://user-images.githubusercontent.com/109258120/208022850-d44d484d-7a97-4d13-869e-f023ff9f12e5.png)
