### ISSUE TITLE
Installation not completed (Husky install)

### ISSUE THREAD

**Issue by Mehdi-YC** [calcom/docker#185]
Hello,
i tried installing this repo more than 4 times and every time it stops here
![image](https://user-images.githubusercontent.com/44881216/207176793-754c3d92-4b80-494d-a3de-e331ef279e2e.png)

and btw , in the readme you forgot to add submodules update  to get the calcom repo

**Comment by PeerRich** [comment]
i dont think you should be using husky install

can you not try

yarn

yarn dx

(with docker running)

**Comment by krumware** [comment]
@Mehdi-YC is this doing the docker build? are you building the image yourself? Apologies, it's difficult to tell from your screenshot

Also, cloning the submodule is not necessary for those strictly using the docker-compose config to pull and run the image, so the submodule update instructions are only in the build instructions.

**Comment by Mehdi-YC** [comment]
thank you , i didn't notice it , i will close this right now
