### ISSUE TITLE
Docker image tagging

### ISSUE THREAD

**Issue by tofran** [calcom/docker#199]
As of right now the Docker image [calcom/cal.com @ docker hub](https://hub.docker.com/r/calcom/cal.com) only has one, non-stable `latest` tag.

Tags should be pushed for each version, or at least, as a starting point the commit `sha` of this repository. This way one could predictably use an image in a production environment without it getting updated. (It is also relevant for debugging as you have one prebuilt static image for a specific version).

**Comment by PeerRich** [comment]
@krumware thoughts on this?

**Comment by krumware** [comment]
I agree with it and it's been planned. Will come shortly

**Comment by krumware** [comment]
@tofran can you please try https://hub.docker.com/r/calcom/cal.com/tags

**Comment by zomars** [comment]
Can we use a GitHub action for this? Will investigate once I'm cleared up

**Comment by krumware** [comment]
We can, it can be as simple as on release here trigger a GitHub action to tag a release in the docker repo

**Comment by PeerRich** [comment]
nice
