### ISSUE TITLE
buiding the container fails due to new preinstall dependencies

### ISSUE THREAD

**Issue by eleith** [calcom/docker#203]
recent changes in the main repository added a preinstall step:

https://github.com/calcom/cal.com/commit/8d078564dda8d9fea38ef562317f95f5378f61ac

these scripts need to be in the container in order for turbo to properly run all steps without error. without them, the build step will error, complaining about a missing `.git-init.sh` script

i have a proposed fix for this in https://github.com/calcom/docker/pull/202

**Comment by krumware** [comment]
The build still fails, but doesn't look like it's due to this same issue, likely is due to some other core changes, but reopening just in case

**Comment by eleith** [comment]
yup, looks like a typescript error. so the `preinstall` script seems to work, but now the web build fails.

**Comment by emrysal** [comment]
Hi both, I'm currently finishing the final touches on version 2.5.3 which I believe fixes the issues seen in the build.

**Comment by krumware** [comment]
> Hi both, I'm currently finishing the final touches on version 2.5.3 which I believe fixes the issues seen in the build.

Thanks!!

**Comment by eleith** [comment]
i was able to successfully build `2.5.3`

**Comment by krumware** [comment]
Latest is up to date!
