### ISSUE TITLE
watchtower automatic update of calendso now is giving 404 error

### ISSUE THREAD

**Issue by cyango** [calcom/docker#204]
I have watchtower container https://containrrr.dev/watchtower/ and it updates the other containers that are on the same socket.

This was updating calendso docker nicely, however now it gives this error:

Could not do a head request for "calendso/calendso:latest", falling back to regular pull.
Reason: registry responded to head request with "404 Not Found", auth: "not present"

Any clue? Maybe a issue with docker tags?

**Comment by krumware** [comment]
that tag is still available https://hub.docker.com/r/calendso/calendso/tags
We are moving to calcom/cal.com, but the calendso org is still getting pushed to

**Comment by cyango** [comment]
Maybe. Will close and reopen if I get it again.
