### ISSUE TITLE
Docker compose up fails with no space on device error

### ISSUE THREAD

**Issue by kvnam** [calcom/docker#206]
Hey,

I'm trying to set up the Calcom docker on an EC2 (t2.large - moved up from small due to the OOM error) but still no luck. Every time I try to run `docker compose up` it fails at 
```
#0 105.0 error Could not write file "/calcom/yarn-error.log": "ENOSPC: no space left on device, open '/calcom/yarn-error.log'"
```

I followed all the steps given in the repo, and also updated the docker image to use `image: calendso/calendso:latest`. No luck. Any suggestions on how I can make this work?

When I try to run a `docker compose pull` I get the same error 

```
WARNING: Some service image(s) must be built from source by running:
    docker compose build calcom
1 error occurred:
	* failed to register layer: Error processing tar file(exit status 1): write /calcom/apps/web/.next/cache/webpack/server-production/0.pack: no space left on device
```
Would appreciate some help in getting this set up and running. Thanks!

**Comment by kvnam** [comment]
Sorry I thought I was posting in Discussions, please disregard

**Comment by krumware** [comment]
What is the size of your EBS volume attached to the instance?

https://forums.docker.com/t/docker-no-space-left-on-device/69205

**Comment by kvnam** [comment]
@krumware - 8GB

**Comment by krumware** [comment]
You're only getting maybe 1-2GB of free space outside of the OS with that size. Are you able to use a slightly larger disk?

**Comment by kvnam** [comment]
Sure, bumping it up to 16GB now. Will post back on build status after I try again, thanks!

**Comment by krumware** [comment]
Just noting, you may have done this, but unless this is launching a new instance with the larger disk, then you also need to expand the partition to take advantage of the new space

**Comment by kvnam** [comment]
Sure @krumware I'll do that as well 👍

**Comment by kvnam** [comment]
@krumware - That resolved it, thank you for helping! Closing the issue now.
