### ISSUE TITLE
URL change in .env doesn't change team URL

### ISSUE THREAD

**Issue by Dickschieder** [calcom/docker#207]
hi there
I changed the .env file from  localhost:3000 to my URL address. It works so far, but when I generate the embetted code or I check the Team address, there is still "localhost:3000" instead of my URL. Is there any other config I have to change additional to NEXT_PUBLIC_WEBAPP_URL?
thanks a lot
Sebastian

**Comment by krumware** [comment]
All you need to do is change that variable then restart the container. You maybe need to delete the container and start a new one.
If that doesn't work, can you please provide the log for your container?

**Comment by Dickschieder** [comment]
hello @krumware 
you're right - I deleted the container and started from beginning. Now it's working. Thanks a lot
