### ISSUE TITLE
Redirect to localhost:3000 after login

### ISSUE THREAD

**Issue by aantilao** [calcom/docker#214]
Hello, i was using docker instalation in production enviorment, but after I logged in, I redirected to localhost:3000.
In my .env var i set  NEXT_PUBLIC_WEBAPP_URL and NEXTAUTH_URL but still redirect to localhost.

The weird part is in docker logs, the replace-placeholder change the localhost to my url.

I tried change the docker version (2.5.4, 2.5.5, 2.5.9, and the latest), but nothing happens.

The migrations applied in my database and IO did nmot have any errors in my logs.

Does anyone else have this happen or know how to fix it?

**Comment by krumware** [comment]
I'm seeing some similar behavior, not with the redirects yet, but in general with browser caching. Can you try in incognito mode just to test?

**Comment by aantilao** [comment]
I tried in incognito and another explorers, but the error still continue,  I read in another post and an option is invalidate cache, and I applied to my distribution, but nothing happens.

**Comment by 3rdgunner** [comment]
Set NEXTAUTH_URL  as local host:3000 that is how I have it on my setup and make sure you clear the cache of the browser

**Comment by krumware** [comment]
We have also noticed this happening occasionally as a caching issue, after attempting login prior to updating the nextauth_url
