### ISSUE TITLE
Pre-built docker image is out of date

### ISSUE THREAD

**Issue by kolaente** [calcom/docker#216]
The docker image in the example docker-compose.yml, `calcom.docker.scarf.sh/calcom/cal.com`, seems to use version 2.6.0 while the latest is 2.6.0.

**Comment by krumware** [comment]
There was an issue with the cal.com core where the version was not properly updated in the package.json, so the UI appeared to be on 2.6.0 even though it was actually 2.6.1/2.6.2.

Will reevaluate alongside build issue with 2.6.3

**Comment by kolaente** [comment]
But the docker image is built on every release?

**Comment by krumware** [comment]
The docker image is built every release and you can also target :main for the nightlies. :v2.6.2 is the tag for the v2 6.2 release

**Comment by krumware** [comment]
This is resolved
