### ISSUE TITLE
Latest versions are not tagged

### ISSUE THREAD

**Issue by kolaente** [calcom/docker#224]
The last 3 versions of cal.com are not built or tagged for [the docker image](https://hub.docker.com/r/calcom/cal.com/tags). The last available version seems to be 2.6.8 while the last release is 2.6.11.

**Comment by krumware** [comment]
2.6.9-2.6.12 building and pushing

**Comment by kolaente** [comment]
Thanks!

**Comment by krumware** [comment]
The versions are tagged in GitHub. We are working to resolve build issues.
