### ISSUE TITLE
Unable to find entry for react-select@npm:5.4.0

### ISSUE THREAD

**Issue by krumware** [calcom/docker#230]
In 2.7.2, it looks like there might be a missing dependency update in /calcom

 > [builder 8/9] RUN yarn config set httpTimeout 1200000 &&     turbo prune --scope=@calcom/web --docker &&     yarn install &&     yarn db-deploy &&     yarn --cwd packages/prisma seed-app-store:
#15 1.374  - Added @calcom/office365video
#15 1.394  - Added @calcom/prisma
#15 1.398  - Added @calcom/trpc
#15 1.399  - Added @calcom/tsconfig
#15 1.401  - Added @calcom/types
#15 1.414  - Added @calcom/ui
#15 1.454  - Added @calcom/web
#15 1.462  - Added @calcom/zoomvideo
#15 1.525  ERROR  Failed to encode pruned lockfile: Unable to find entry for react-select@npm:5.4.0
#15 1.525 Turbo error: Failed to encode pruned lockfile: Unable to find entry for react-select@npm:5.4.0
------
Dockerfile:27

**Comment by emrysal** [comment]
Should be fixed now @krumware - regenerated the lockfile and appended the commit to v2.7.2 - please confirm

**Comment by krumware** [comment]
This is fixed!
