### ISSUE TITLE
Version tagged in Git does not reflect Docker Image

### ISSUE THREAD

**Issue by mritzmann** [calcom/docker#239]
## Problem

https://github.com/calcom/docker/blob/072ac8940c64ea8692494d036c651a8f246323b2/docker-compose.yaml#L23-L24

The docker images in `docker-compose.yaml` are specified without a version. The calcom version used is therefore not dependent on the git tag, but on the version pushed by the maintainers to `calcom.docker.scarf.sh/calcom/cal.com`.

This leads me to the following problem:

1. I subscribe to the GitHub repo to be informed about new releases
2. A new release is tagged, for example `v2.8.12`
3. I want to apply the `v2.8.12` update, checkout the tag, pull and start new containers
4. I notice that my version is still on `v2.8.10`
5. I try again in 24h until the version match, back to step 3

## Steps to reproduce

```shell
git checkout v2.8.12
docker compose pull
docker compose up -d
```

Access web app. Version according to footer:

> © 2023 Cal.com, Inc. v.2.8.10-sh-ce

## Questions

My question now is:

* Is this intentional and if so, is there a better way to keep calcom up to date?
* Or is there a subscribable release note somewhere that matches the published docker image?

In my mind, the Docker image in `docker-compose.yaml` should always be tagged with a unique versiontag.

**Comment by Harshkumar2000** [comment]
the Docker image in docker-compose.yaml should always be tagged with a unique versiontag. --> Yes ,your are right .
 
If you want to use a specific version of the image calcom.docker.scarf.sh/calcom/cal.com instead of relying on the latest version, you can specify the version in your docker-compose.yaml file.

You can update the image field in your docker-compose.yaml file to include the specific version of the image you want to use, like this:

image: calcom.docker.scarf.sh/calcom/cal.com:v2.8.12

this will solve you issue

**Comment by mritzmann** [comment]
Thank you for your reply.

> You can update the image field in your docker-compose.yaml file to include the specific version
> (..) this will solve you issue

Almost.

The same problem remains: There is still the problem that an update which was tagged is not available.

* On GitHub the version `v2.8.10` was tagged
* But a Docker image with version `v2.8.10` does not exist at the moment

```shell
$ docker pull calcom.docker.scarf.sh/calcom/cal.com:v2.8.12
Error response from daemon: manifest for calcom.docker.scarf.sh/calcom/cal.com:v2.8.12 not found: manifest unknown: manifest unknown
```

**Comment by krumware** [comment]
Hi folks. 2.8.12 was tagged as latest in the git repo, but the  build is failing and failed to push the image. In the meantime, I will remove the 2.8.12 build and tag 2.8.11 as latest.

**Comment by mritzmann** [comment]
> In the meantime, I will remove the 2.8.12 build and tag 2.8.11 as latest.

`:v2.8.11` and `:latest` have the same sha256 hash, so they are the same, as you say.

```shell
$ docker pull calcom.docker.scarf.sh/calcom/cal.com:v2.8.11
v2.8.11: Pulling from calcom/cal.com
Digest: sha256:45c270545a543d8c30fe9dd84367986cecf8ff58b10d5bc09413c895b1b93d04
Status: Downloaded newer image for calcom.docker.scarf.sh/calcom/cal.com:v2.8.11
calcom.docker.scarf.sh/calcom/cal.com:v2.8.11

$ docker pull calcom.docker.scarf.sh/calcom/cal.com:latest 
latest: Pulling from calcom/cal.com
Digest: sha256:45c270545a543d8c30fe9dd84367986cecf8ff58b10d5bc09413c895b1b93d04
Status: Image is up to date for calcom.docker.scarf.sh/calcom/cal.com:latest
calcom.docker.scarf.sh/calcom/cal.com:latest
```

But as soon as I run one of them, I see the following in the web interface:

> © 2023 Cal.com, Inc. v.2.8.10-sh-ce

Sorry to say this, but I still find the whole process around n8n update very confusing  :sweat_smile:. But maybe this is just a special situation, because of the faulty build. I will just wait and see how this develops over the next days or weeks.
