### ISSUE TITLE
Who is maintaining this repo?

### ISSUE THREAD

**Issue by pat-s** [calcom/docker#24]
As stated in the [README of Calendso](https://github.com/calendso/calendso#docker), the docker repo is a community project and not officially supported by the Calendso team.

However, it is unclear how one can contribute here and who is actively maintaining this repo.
Also getting write permissions needs an invite from the Calendso team again which might not be that easy. It would be great to have some instructions how one can contribute here.

Currently there are several issues with the current state of the repo and I fear that this repo becomes outdated if no action is taken.

**Comment by PeerRich** [comment]
hey @pat-s, yeah i agree this has been very confusing. any recommendations? do you want to contribute to it? We can make a new team that has some writing authority over this repo

**Comment by PeerRich** [comment]
hey @pat-s we've given this topic a much higher priority inside of the team and will find a better solution for this! 🎉  until then, you can make PRs at any time and we'll merge them accordingly
