### ISSUE TITLE
Failing to get google calendar work in selfhosted calcom

### ISSUE THREAD

**Issue by buzzard10** [calcom/docker#253]
Hello :)
I'm really thankful for this not small piece of software! It's really useful! 
I've manage to make it work on my server, but i have issue with one thing - google calendar integration.

I'm using for work microsoft office calendar and for private things google calendar. I would like to connect them both to calcom.
I would like calcom to check my availability in both services. As far I've managed to setup microsoft office calendar, i have problems with google calendar. 

- I've installed google calendar app
- I've created google app for this integration in google console
- I've added keys to calcom for google integration
- I've log in to google integration on my private account and approved permissions for calcom to calendar

Unfortunately, after all these steps it's not working. After i'm trying to go to Apps > Installed i have only loading screen:
![image](https://github.com/calcom/docker/assets/17282191/05ea406a-70b2-4411-983b-0895371f005b)

**Comment by krumware** [comment]
can you please provide a de-identified version of your env variable for the calendar?

**Comment by buzzard10** [comment]
@krumware I've simply add keys in calcom admin settings, should i add this in .env? If so, can you give me proper json array with proper params for that?

It'll work in way which will check availability in my private calendars as well? :)

**Comment by krumware** [comment]
I've had to add the `GOOGLE_API_CREDENTIALS={"web":{"client_id":"...` after following the cal.com instructions, to have the google calendar options to show. Give it a shot and let me know if that helps it on your end!

**Comment by buzzard10** [comment]
@krumware Oh Man! You saved my day!!! 
Thank you very much!!!!

Now i can see all my private calendars! So if i check one of them they'll be taken into consideration while checking my availability? :D
