### ISSUE TITLE
Problem with timezones in Cal.com

### ISSUE THREAD

**Issue by buzzard10** [calcom/docker#260]
Hello Guys,
as you can see below we have a lot of countries in GMT+2 timezone. Unfortunately they're not available on timezones list in Cal.com. It may be weird for customers..

![image](https://github.com/calcom/docker/assets/17282191/63ce850d-d81a-4e93-ae6c-291ac532b173)

List of countries in Cal.com:
![image](https://github.com/calcom/docker/assets/17282191/5bf8966c-37f3-4c29-a873-12587f54779e)

**Comment by krumware** [comment]
Would this be best to open over on calcom/cal.com?

**Comment by buzzard10** [comment]
Okay, i'll do that. :)
