### ISSUE TITLE
Issue with pulling the latest image

### ISSUE THREAD

**Issue by buzzard10** [calcom/docker#267]
Hello,
i have problem with pulling the newest image of calcom docker. I'm using `docker compose pull` and it says that i have newest versions, but after starting containers i have © 2023 [Cal.com, Inc.](https://go.cal.com/credits) [v.3.0.7-sh](https://go.cal.com/releases) in my cal.com dashboard. The newest version is 3.0.10.

How can i fetch the newest version? Maybe it's because in docker-compose i'm using `calcom.docker.scarf.sh/calcom/cal.com`?

**Comment by krumware** [comment]
3.0.10 hasn't hit the docker release yet, will update that this morning.

You should be seeing 3.0.9 though, I'll double check this morning.

**Comment by buzzard10** [comment]
I don't see even 3.0.8. Maybe i should use official docker hub image?
Thank you for checking.

**Comment by krumware** [comment]
Sure, try switching to the official. It's possible that the scarf endpoint has additional caching.
At times, the cal.com package has missed the version bump internal to the UI, which could also be happening. I think I've seen a couple of PRs recently to fix the package.json tagged version, which could be related.

Here's the dockerhub official
https://hub.docker.com/repository/docker/calcom/cal.com/general

Also, `latest` is the latest tagged version, `main` is the nightly built version (canary)

**Comment by buzzard10** [comment]
So what, i should change `image: calcom.docker.scarf.sh/calcom/cal.com` to `image: calcom/cal.com:v3.0.9`? 
Do you know how long it'll take to fix this issue?

**Comment by mritzmann** [comment]
Related topic: #239 Using Docker tags would be more transparent.

**Comment by buzzard10** [comment]
Thank you, now it's okay :)
