### ISSUE TITLE
fetch failed in CLIENT_FETCH_ERROR

### ISSUE THREAD

**Issue by Leonct23** [calcom/docker#294]
Hello, help me, the password has already been created with the first user, including encrypted, but this error continues, there seems to be an error when accessing the printscreen api url.

Log container docker
![image](https://github.com/calcom/docker/assets/147319543/f6b7812f-caf8-4a31-a1dd-b95bc24cb908)

I tested the url via curl -i but there is no access.
![image](https://github.com/calcom/docker/assets/147319543/91352269-30b3-442f-ba70-aed96ed57029)

**Comment by voska** [comment]
Change your `NEXTAUTH_URL` to `http://localhost:3000/api/auth/csrf`
