### ISSUE TITLE
robots.txt Indexing #IMPORTANT

### ISSUE THREAD

**Issue by prononext** [calcom/docker#314]
How do I rejects any indexing from search engines on a self hosted instance ruuning on docker=

**Comment by voska** [comment]
You could fork calcom/cal.com and edit robots.txt https://github.com/calcom/cal.com/blob/main/apps/web/public/robots.txt then build your own image.

**Comment by prononext** [comment]
Yes I can map a robots.txt into the container also, but would be nice to just have a security settings to set your robots.txt in the GUI as its a basic privacy setting which should not require building a own image or mapping some file into your docker container.
