### ISSUE TITLE
Issue with docker hub images

### ISSUE THREAD

**Issue by buzzard10** [calcom/docker#329]
Hello Guys,
i don't know why but last tag on docker hub is 3.7.16.
The newest release on github is 3.8.0-rc

https://hub.docker.com/r/calcom/cal.com/tags

**Comment by keithwillcode** [comment]
@buzzard10 hey sorry for the issues. We are actively looking at why these are failing.

**Comment by mariushosting** [comment]
@keithwillcode The latest calcom docker version has stopped to work.  The most recently Calcom Docker version that work is version **3.7.11** and version under 3.7.11

Version 3.7.15, 3.7.16 give the following error message:

 yarn start
• Packages in scope: @calcom/web
• Running start in 1 packages
• Remote caching disabled
@calcom/web:start: cache bypass, force executing b0182874aa91d7f3
@calcom/web:start: Duplicate value found in common.json keys:   seats_available_other and seats_available_one
@calcom/web:start: Duplicate value found in common.json keys:   location_variable and location
@calcom/web:start: Duplicate value found in common.json keys:   additional_notes_variable and additional_notes
@calcom/web:start: Duplicate value found in common.json keys:   already_have_account and already_have_an_account
@calcom/web:start: Duplicate value found in common.json keys:   timezone_variable and timezone
@calcom/web:start: Duplicate value found in common.json keys:   scheduling_for_your_team and workflow_automation
@calcom/web:start: Duplicate value found in common.json keys:   saml_sso and saml_config
@calcom/web:start: Duplicate value found in common.json keys:   advanced_managed_events_description and unified_billing_description
@calcom/web:start:   ▲ Next.js 13.5.5
@calcom/web:start:   - Local:        http://localhost:3000
@calcom/web:start: 
@calcom/web:start:  ✓ Ready in 1283ms
@calcom/web:start: 00:54:26:588	ERROR[redactError] Error:  {"name":"PrismaClientKnownRequestError","code":"P2021","clientVersion":"5.4.2","meta":{"table":"public.Feature"}}
@calcom/web:start: PrismaClientKnownRequestError: 
@calcom/web:start: Invalid `prisma.user.count()` invocation:
@calcom/web:start: 
@calcom/web:start: 
@calcom/web:start: The table `public.users` does not exist in the current database.
@calcom/web:start:     at Cn.handleRequestError (/calcom/node_modules/@prisma/client/runtime/library.js:123:6817)
@calcom/web:start:     at Cn.handleAndLogRequestError (/calcom/node_modules/@prisma/client/runtime/library.js:123:6206)
@calcom/web:start:     at Cn.request (/calcom/node_modules/@prisma/client/runtime/library.js:123:5926)
@calcom/web:start:     at async l (/calcom/node_modules/@prisma/client/runtime/library.js:128:9968)
@calcom/web:start:     at async getServerSideProps (/calcom/apps/web/.next/server/pages/auth/login.js:1:10204) {
@calcom/web:start:   code: 'P2021',
@calcom/web:start:   clientVersion: '5.4.2',
@calcom/web:start:   meta: { table: 'public.users' }
@calcom/web:start: }
@calcom/web:start: react-i18next:: You will need to pass in an i18next instance by using initReactI18next

**Comment by buzzard10** [comment]
@mariushosting hello! 
I can confirm that i have similar issue. After i've upgrade to the newest available image, i can't log in because i have error 500. 

And Mariushosting, thank you for your great work! I'm a fan of your blog ;)

**Comment by mariushosting** [comment]
> @mariushosting hello! I can confirm that i have similar issue. After i've upgrade to the newest available image, i can't log in because i have error 500.
> 
> And Mariushosting, thank you for your great work! I'm a fan of your blog ;)

In the meantime change the image calcom/cal.com:latest with image: calcom/cal.com:v3.7.11

**Comment by buzzard10** [comment]
@mariushosting i've already did that. Hope community will be able to figure out the problem and we'll be able to use it :)

**Comment by mariushosting** [comment]
> @mariushosting i've already did that. Hope community will be able to figure out the problem and we'll be able to use it :)

Awesome! Just wait for @keithwillcode to look into this!

**Comment by lejacobroy** [comment]
I have the same problem on my end, I confirm that the v3.7.11 tag is working.
Here's the anonymized logs if I start the v3.7.15 or newer builds:

`✔ Container database  Created                                                                                                                                0.0s 
 ✔ Container calcom    Recreated                                                                                                                              0.3s 
Attaching to calcom, database
database  | 
database  | PostgreSQL Database directory appears to contain a database; Skipping initialization
database  | 
database  | 2024-02-21 16:14:08.001 UTC [1] LOG:  starting PostgreSQL 16.2 (Debian 16.2-1.pgdg120+2) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
database  | 2024-02-21 16:14:08.002 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
database  | 2024-02-21 16:14:08.002 UTC [1] LOG:  listening on IPv6 address "::", port 5432
database  | 2024-02-21 16:14:08.019 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
database  | 2024-02-21 16:14:08.039 UTC [29] LOG:  database system was shut down at 2024-02-21 16:12:12 UTC
database  | 2024-02-21 16:14:08.073 UTC [1] LOG:  database system is ready to accept connections
calcom    | + scripts/replace-placeholder.sh http://localhost:3000 https://mywebsite
calcom    | Replacing all statically built instances of http://localhost:3000 with https://mywebsite.
calcom    | + scripts/wait-for-it.sh database:5432 -- echo database is up
calcom    | nc command is missing!
calcom    | + npx prisma migrate deploy --schema /calcom/packages/prisma/schema.prisma
calcom    | Prisma schema loaded from packages/prisma/schema.prisma
calcom    | Datasource "db": PostgreSQL database
calcom    | 
calcom    | Error: Prisma schema validation - (get-config wasm)
calcom    | Error code: P1012
calcom    | error: Environment variable not found: DATABASE_DIRECT_URL.
calcom    |   -->  schema.prisma:7
calcom    |    | 
calcom    |  6 |   url       = env("DATABASE_URL")
calcom    |  7 |   directUrl = env("DATABASE_DIRECT_URL")
calcom    |    | 
calcom    | 
calcom    | Validation Error Count: 1
calcom    | [Context: getConfig]
calcom    | 
calcom    | Prisma CLI Version : 5.4.2
calcom    | npm notice 
calcom    | npm notice New minor version of npm available! 10.2.3 -> 10.4.0
calcom    | npm notice Changelog: <https://github.com/npm/cli/releases/tag/v10.4.0>
calcom    | npm notice Run `npm install -g npm@10.4.0` to update!
calcom    | npm notice 
calcom    | + npx ts-node --transpile-only /calcom/packages/prisma/seed-app-store.ts
calcom    | 📲 Updated app: 'apple-calendar'
calcom    | 📲 Updated app: 'caldav-calendar'
calcom    | Error adding google credentials to DB: Cannot destructure property 'client_secret' of 'JSON.parse(...).web' as it is undefined.
calcom    | 📲 Updated app: 'office365-calendar'
calcom    | 📲 Updated app: 'msteams'
calcom    | 📲 Updated app: 'zoom'
calcom    | 📲 Updated app: 'jitsi'
calcom    | 📲 Updated app: 'wipe-my-cal'
calcom    | 📲 Updated app: 'make'
calcom    | 📲 Updated app: 'huddle01'
calcom    | 📲 Updated app: 'alby'
calcom    | 📲 Updated app: 'amie'
calcom    | 📲 Updated app: 'apple-calendar'
calcom    | 📲 Updated app: 'around'
calcom    | 📲 Updated app: 'basecamp3'
calcom    | 📲 Updated app: 'cal-ai'
calcom    | 📲 Updated app: 'caldav-calendar'
calcom    | 📲 Updated app: 'campfire'
calcom    | 📲 Updated app: 'closecom'
calcom    | 📲 Updated app: 'cron'
calcom    | 📲 Updated app: 'daily-video'
calcom    | 📲 Updated app: 'deel'
calcom    | 📲 Updated app: 'discord'
calcom    | 📲 Updated app: 'eightxeight'
calcom    | 📲 Updated app: 'element-call'
calcom    | 📲 Updated app: 'exchange2013-calendar'
calcom    | 📲 Updated app: 'exchange2016-calendar'
calcom    | 📲 Updated app: 'exchange'
calcom    | 📲 Updated app: 'facetime'
calcom    | 📲 Updated app: 'fathom'
calcom    | 📲 Updated app: 'feishu-calendar'
calcom    | 📲 Updated app: 'ga4'
calcom    | 📲 Updated app: 'giphy'
calcom    | 📲 Updated app: 'google-calendar'
calcom    | 📲 Updated app: 'google-meet'
calcom    | 📲 Updated app: 'gtm'
calcom    | 📲 Updated app: 'hubspot'
calcom    | 📲 Updated app: 'huddle01'
calcom    | 📲 Updated app: 'ics-feed'
calcom    | 📲 Updated app: 'intercom'
calcom    | 📲 Updated app: 'jitsi'
calcom    | 📲 Updated app: 'lark-calendar'
calcom    | 📲 Updated app: 'make'
calcom    | 📲 Updated app: 'matomo'
calcom    | 📲 Updated app: 'metapixel'
calcom    | 📲 Updated app: 'mirotalk'
calcom    | 📲 Updated app: 'mock-payment-app'
calcom    | 📲 Updated app: 'n8n'
calcom    | 📲 Updated app: 'office365-calendar'
calcom    | 📲 Updated app: 'msteams'
calcom    | 📲 Updated app: 'paypal'
calcom    | 📲 Updated app: 'ping'
calcom    | 📲 Updated app: 'pipedream'
calcom    | 📲 Updated app: 'pipedrive-crm'
calcom    | 📲 Updated app: 'plausible'
calcom    | 📲 Updated app: 'qr_code'
calcom    | 📲 Updated app: 'raycast'
calcom    | 📲 Updated app: 'riverside'
calcom    | 📲 Updated app: 'roam'
calcom    | 📲 Updated app: 'routing-forms'
calcom    | 📲 Updated app: 'salesforce'
calcom    | 📲 Updated app: 'salesroom'
calcom    | 📲 Updated app: 'sendgrid'
calcom    | 📲 Updated app: 'shimmervideo'
calcom    | 📲 Updated app: 'signal'
calcom    | 📲 Updated app: 'sirius_video'
calcom    | 📲 Updated app: 'skiff'
calcom    | 📲 Updated app: 'stripe'
calcom    | 📲 Updated app: 'sylapsvideo'
calcom    | 📲 Updated app: 'tandem'
calcom    | 📲 Updated app: 'telegram'
calcom    | 📲 Updated app: 'typeform'
calcom    | 📲 Updated app: 'vimcal'
calcom    | 📲 Updated app: 'vital-automation'
calcom    | 📲 Updated app: 'weather_in_your_calendar'
calcom    | 📲 Updated app: 'webex'
calcom    | 📲 Updated app: 'whatsapp'
calcom    | 📲 Updated app: 'whereby'
calcom    | 📲 Updated app: 'wipe-my-cal'
calcom    | 📲 Updated app: 'wordpress'
calcom    | 📲 Updated app: 'zapier'
calcom    | 📲 Updated app: 'zoho-bigin'
calcom    | 📲 Updated app: 'zohocalendar'
calcom    | 📲 Updated app: 'zohocrm'
calcom    | 📲 Updated app: 'zoom'
database  | 2024-02-21 16:14:16.806 UTC [33] ERROR:  column users.movedToProfileId does not exist at character 1281
database  | 2024-02-21 16:14:16.806 UTC [33] STATEMENT:  SELECT "public"."users"."id", "public"."users"."username", "public"."users"."name", "public"."users"."email", "public"."users"."emailVerified", "public"."users"."password", "public"."users"."bio", "public"."users"."avatar", "public"."users"."avatarUrl", "public"."users"."timeZone", "public"."users"."weekStart", "public"."users"."startTime", "public"."users"."endTime", "public"."users"."bufferTime", "public"."users"."hideBranding", "public"."users"."theme", "public"."users"."created", "public"."users"."trialEndsAt", "public"."users"."defaultScheduleId", "public"."users"."completedOnboarding", "public"."users"."locale", "public"."users"."timeFormat", "public"."users"."twoFactorSecret", "public"."users"."twoFactorEnabled", "public"."users"."backupCodes", "public"."users"."identityProvider"::text, "public"."users"."identityProviderId", "public"."users"."invitedTo", "public"."users"."brandColor", "public"."users"."darkBrandColor", "public"."users"."away", "public"."users"."allowDynamicBooking", "public"."users"."allowSEOIndexing", "public"."users"."receiveMonthlyDigestEmail", "public"."users"."metadata", "public"."users"."verified", "public"."users"."role"::text, "public"."users"."disableImpersonation", "public"."users"."organizationId", "public"."users"."locked", "public"."users"."movedToProfileId" FROM "public"."users" WHERE "public"."users"."username" = $1 LIMIT $2 OFFSET $3
calcom    | PrismaClientKnownRequestError: 
calcom    | Invalid `prisma.user.findFirst()` invocation:
calcom    | 
calcom    | 
calcom    | The column `users.movedToProfileId` does not exist in the current database.
calcom    |     at Cn.handleRequestError (/calcom/node_modules/@prisma/client/runtime/library.js:123:6817)
calcom    |     at Cn.handleAndLogRequestError (/calcom/node_modules/@prisma/client/runtime/library.js:123:6206)
calcom    |     at Cn.request (/calcom/node_modules/@prisma/client/runtime/library.js:123:5926)
calcom    |     at async l (/calcom/node_modules/@prisma/client/runtime/library.js:128:9968)
calcom    |     at async seedAppData (/calcom/packages/prisma/seed-app-store.ts:31:19)
calcom    |     at async main (/calcom/packages/prisma/seed-app-store.ts:384:3) {
calcom    |   code: 'P2022',
calcom    |   clientVersion: '5.4.2',
calcom    |   meta: { column: 'users.movedToProfileId' }
calcom    | }
calcom    | + yarn start
calcom    | • Packages in scope: @calcom/web
calcom    | • Running start in 1 packages
calcom    | • Remote caching disabled
calcom    | @calcom/web:start: cache bypass, force executing 2f6df2db2c5d3dbe
calcom    | @calcom/web:start: Duplicate value found in common.json keys:   seats_available_other and seats_available_one
calcom    | @calcom/web:start: Duplicate value found in common.json keys:   location_variable and location
calcom    | @calcom/web:start: Duplicate value found in common.json keys:   additional_notes_variable and additional_notes
calcom    | @calcom/web:start: Duplicate value found in common.json keys:   already_have_account and already_have_an_account
calcom    | @calcom/web:start: Duplicate value found in common.json keys:   timezone_variable and timezone
calcom    | @calcom/web:start: Duplicate value found in common.json keys:   scheduling_for_your_team and workflow_automation
calcom    | @calcom/web:start: Duplicate value found in common.json keys:   saml_sso and saml_config
calcom    | @calcom/web:start: Duplicate value found in common.json keys:   advanced_managed_events_description and unified_billing_description
calcom    | @calcom/web:start:   ▲ Next.js 13.5.5
calcom    | @calcom/web:start:   - Local:        http://localhost:3000
calcom    | @calcom/web:start: 
calcom    | @calcom/web:start:  ✓ Ready in 978ms
`

So it seems like the ENV variables changed and need to add 'DATABASE_DIRECT_URL'.
In my `.env` file, I added an entry for this variable, with the same value as the older 'DATABASE_URL' variable.
With that change, I can run the v3.7.15 tags up to the latest available (v3.7.16).

**Comment by xcellentavi** [comment]
> So it seems like the ENV variables changed and need to add 'DATABASE_DIRECT_URL'. In my `.env` file, I added an entry for this variable, with the same value as the older 'DATABASE_URL' variable. With that change, I can run the v3.7.15 tags up to the latest available (v3.7.16).

Is that all that needs to be done to correct these errors? And we need both variables DATABASE_URL and DATABASE_DIRECT_URL?

**Comment by MarioNoll** [comment]
See https://github.com/calcom/docker/issues/323

>Is that all that needs to be done to correct these errors? And we need both variables DATABASE_URL and DATABASE_DIRECT_URL?

Adding `DATABASE_DIRECT_URL` did not change anything for me.

**Comment by NexusEFR** [comment]
Working for me latest tags after adding env variable, in unraid server...thanks!

**Comment by buzzard10** [comment]
Any updates regarding availability of newest versions on docker hub?

**Comment by xcellentavi** [comment]
> Any updates regarding availability of newest versions on docker hub?

My container on unraid is running v.3.8.6-sh according to what I see at the bottom left corner of my settings page.

v3.8.6 is showing as the latest release on github: https://github.com/calcom/cal.com/releases

The repo on docker hub matches also: https://hub.docker.com/r/calcom/cal.com/tags

I was running 3.8.5-sh yesterday, but docker hub is only showing v3.7.16 as the previous tag, so not sure why it doesn't have anything in between.

**Comment by NexusEFR** [comment]
Wow, great! I did not know that you could see the version of the image docker on the page of the platform cal.com selfhosted..Attachment screen capture with the image .. and what I see still not in the last image updated, but comment higher between v3.7.11 and the last there were errors that did not let enter to log in until entering the variables of environment mentioned..

![image](https://github.com/calcom/docker/assets/68002188/495a6587-9e94-43cd-8141-22dae8a0271c)

**Comment by buzzard10** [comment]
After upgrade i have this issue:
![image](https://github.com/calcom/docker/assets/17282191/f6319be8-834c-47a9-ba93-c52094015280)

**Comment by NexusEFR** [comment]
> After upgrade i have this issue: ![image](https://private-user-images.githubusercontent.com/17282191/310567437-f6319be8-834c-47a9-ba93-c52094015280.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3NDE0MjgsIm5iZiI6MTcwOTc0MTEyOCwicGF0aCI6Ii8xNzI4MjE5MS8zMTA1Njc0MzctZjYzMTliZTgtODM0Yy00N2E5LWJhOTMtYzUyMDk0MDE1MjgwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA2VDE2MDUyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA3ZjUxN2Q5ZGE4NDBlYzkyODUyZDg5MDRlNTFmNTM3NmEwY2I2OWU4OTA3ZjczMTNjMzIzZjc3OTRjYmQ5ZTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.m0fpwg4e0AQ6PzaudkM7JHGhhByq26ecQ_hRjB7OCsI) There is also log from docker: ![image](https://private-user-images.githubusercontent.com/17282191/310569302-36fbfd38-68ef-4c7e-a356-6a87990ce3d9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3NDE0MjgsIm5iZiI6MTcwOTc0MTEyOCwicGF0aCI6Ii8xNzI4MjE5MS8zMTA1NjkzMDItMzZmYmZkMzgtNjhlZi00YzdlLWEzNTYtNmE4Nzk5MGNlM2Q5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA2VDE2MDUyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiNGMyYTY2NTQ3NTY2MDJiMjg3OTIyNTdkYzEyNGZjYjhmM2U3NjE4MmE2ZmQyNTNlMTFlMTAxYzA5MWFmODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9HuaXGPULQMxC_NTMo-I7OiW_v-3g1tAAMemeDjUIJo)

From which image of docker do you update? Do you have `DATABASE_DIRECT_URL` variables in your template?

**Comment by buzzard10** [comment]
Image: calcom/cal.com:v3.8.6
There is a `DATABASE_URL` param, but i don't see `DATABASE_DIRECT_URL`.

**Comment by NexusEFR** [comment]
Create that variable `DATABASE_DIRECT_URL` and put the same data as you have in the variable `DATABASE_URL`

**Comment by buzzard10** [comment]
Now it seems working, thank you very much! :)
