### ISSUE TITLE
Update hub.docker

### ISSUE THREAD

**Issue by JSanchezFDZ** [calcom/docker#347]
Hello team!

Please upgrade to the latest version in the Docker Hub: URLhttps://hub.docker.com/r/calcom/cal.com/

Thank you!

**Comment by PhilRW** [comment]
Agreed - latest Docker hub build is v3.9.1

**Comment by intersecato** [comment]
Yes, it's related. All new builds after 3.9.1 are not being published due to errors during the docker image build phase.

**Comment by xcellentavi** [comment]
It's being worked on and they will hopefully have it working soon for us.  Also mentioned here: https://github.com/calcom/cal.com/issues/13242

**Comment by xcellentavi** [comment]
> Any updates?

@JSanchezFDZ, they closed https://github.com/calcom/cal.com/issues/13242 and I see v.4.0.8 available on docker hub.  Looks like everything is working again.
