### ISSUE TITLE
domain/embed/embed.js returns 404 error

### ISSUE THREAD

**Issue by DerLeole** [calcom/docker#360]
The current docker container doesnt seem to provide the embed.js file that is needed for fully selfhosted embeds.

**Comment by buzzard10** [comment]
I have the same problem 😢

**Comment by fedenelli** [comment]
Same here. /embed/embed.js returns 404. Rolled back to version 3.9.1 until v4 is fixed.
<img width="1721" alt="image" src="https://github.com/calcom/docker/assets/28237870/c0f6c631-1a98-44e7-b891-75ef5913134f">

**Comment by Qodestackr** [comment]
Rollback the lib as new version uses:
    useEffect(() => {
        (async function () {
            const cal = await getCalApi({});//await getCalApi({ "embedLibUrl": "http://localhost:3000/embed/embed.js" });
            cal("ui", { "styles": { "branding": { "brandColor": "#000000" } }, "hideEventTypeDetails": false, "layout": "month_view" });
        })();
    }, [])

**Comment by Lars-** [comment]
I found a workaround. Replace the url ending with embed/embed.js with https://app.cal.com/embed/embed.js or even better, download the file and serve it from your own domain.

It would be better if this gets fixed, but at least we can use the embed functionality this way.

**Comment by nepomuc** [comment]
This was already an issue last September (https://github.com/calcom/cal.com/issues/11068). @PeerRich said it was resolved but it's definitely back. :/

**Comment by PeerRich** [comment]
investigating

**Comment by hariombalhara** [comment]
Are you guys using the latest docker version?  I am setting up docker at the moment but I don't see any issue with the code related to this.

There was an issue a month back for a brief period which was fixed.

**Comment by nepomuc** [comment]
@hariombalhara Thanks! Now waiting for your pull request to be merged to main :)
