### ISSUE TITLE
Anyone can create an account on my calcom instance

### ISSUE THREAD

**Issue by techsupportkoeln** [calcom/docker#392]
Is it intended that any user can create an account on my self-hosted calcom instance? Simply click on “Don’t have an account?” when you log in.
And as an admin I can't see how many accounts there are.

**Comment by kamellperry** [comment]
You have to go to the settings (under `admin -> features`) and enable the `disable-signup` feature flag.

![CleanShot 2024-11-21 at 16 55 00@2x](https://github.com/user-attachments/assets/fae8dcb6-4eea-4604-b31a-9660b5172ace)

**Comment by kamellperry** [comment]
And viewing all signed up users is a commercial feature only.

**Comment by techsupportkoeln** [comment]
thanks for your answer. I didn't realize that i have to set the flag.

**Comment by kamellperry** [comment]
@techsupportkoeln you should close this issue
