### ISSUE TITLE
+)HERE'S*!! UFC 310 Live Streams Free to Watch? Pantoja vs Asakura PPV Streaming Details 7 DEC 2024

### ISSUE THREAD

**Issue by osdevfrias22** [calcom/docker#400]
Las Vegas will host a stacked fight card this evening, as UFC 310 culminates in a flyweight title clash and a No 1 contender’s bout at 170lbs.

[CLICK HERE TO WATCH LIVE STREAM](https://tvchannelpass.live/ufc-310)

[CLICK HERE TO WATCH LIVE STREAM](https://tvchannelpass.live/ufc-310)

[CLICK HERE TO WATCH LIVE STREAM](https://tvchannelpass.live/ufc-310)

In the main event, Alexandre Pantoja defends his belt against UFC debutant Kai Asakura, who previously held bantamweight gold in Rizin.

That contest is set to be a dynamic affair, but many eyes are on the co-main event, as Shavkat Rakhmonov faces fellow unbeaten welterweight – and former training partner – Ian Machado Garry.

The winner of that fight is set to challenge Belal Muhammad for the title next, after the champion was forced to withdraw from UFC 310 – and a defence against Rakhmonov – due to an infection.

Here’s all you need to know. We may earn commission from some of the links in this article, but we never allow this to influence our content. This revenue helps to fund journalism across The Independent.

UFC 310 takes place on Saturday 7 December at the T-Mobile Arena in Las Vegas.

The early prelims are due to begin at 11pm GMT (3pm PT, 5pm CT, 6pm ET), with the regular prelims following at 1am GMT on Sunday (5pm PT, 7pm CT, 8pm ET on Saturday). The main card is then set for 3am GMT on Sunday (7pm PT, 9pm CT, 10pm ET on Saturday).

How can I watch it?

The card will air live on TNT Sports in the UK, with the broadcaster’s app and website also streaming the fights. Discovery+ will also air the action in the UK. In the US, ESPN+ will stream the event live, as will the UFC’s Fight Pass.

If you want to stream major sporting events while you are travelling or watching from abroad you’ll need a VPN. Get the best VPN deals in the UK. Viewers using a VPN need to make sure that they comply with any local regulations where they are, and also with the terms of their service provider.

Odds

Ian Machado Garry after beating Geoff Neal via decision in February
open image in gallery
Ian Machado Garry after beating Geoff Neal via decision in February (Getty Images)
Rakhmonov – 2/7; Machado Garry – 12/5

Pantoja – 2/5; Asakura – 2/1

Via Betway. Get all the latest UFC betting sites’ offers. The Independent vets betting sites for useability, security and responsible gambling tools. You can claim free bets here to use across a range of sports. Please read the terms.

Full card (subject to change)

Main card

Alexandre Pantoja (C) vs Kai Asakura (men’s flyweight title)

Shavkat Rakhmonov vs Ian Machado Garry (welterweight, five rounds)

Ciryl Gane vs Alexander Volkov 2 (heavyweight)

Bryce Mitchell vs Kron Gracie (featherweight)

Nate Landwehr vs Dooho Choi (featherweight)

**Comment by tiakal4s** [comment]
dfgdf

**Comment by JannatRita** [comment]
g

**Comment by svbnmghfd** [comment]
dfdff
