### ISSUE TITLE
Allow setting all env variables at runtime

### ISSUE THREAD

**Issue by TheBestMoshe** [calcom/docker#56]
Currently, we need to set the environment variables at build time. This is because Next.js includes them in the final bundle.

It would be better if we can build a generic Docker image, and inject the environment variables at runtime.

See this [discussion](https://github.com/vercel/next.js/discussions/17641#discussioncomment-339555) which has a way of doing it.

I am working on a Home Assistant addon for Calendso, and I have successfully built and run the project using this method. The addon is still in the experimental stages, however, you can see an example of the relevant code. [Here](https://github.com/TheBestMoshe/home-assistant-addons/blob/b001d62c545aead8e98d7e443e2c2835dfba498a/cal.com/Dockerfile#L17) a variable is set with a dummy value during build time. [Here](https://github.com/TheBestMoshe/home-assistant-addons/blob/b001d62c545aead8e98d7e443e2c2835dfba498a/cal.com/docker-entrypoint.sh#L21-L25) the variable values are overwritten at runtime.

**Comment by krumware** [comment]
Do you have enough to do a pull request so that we can see the method in action?

**Comment by krumware** [comment]
@TheBestMoshe just wondering if you might have time to make a specific pull request with just the runtime injection workaround?

**Comment by TheBestMoshe** [comment]
@krumware I began working on this, however, I'm not sure why it was not working for this repo. 

[This](https://github.com/calendso/docker/compare/main...TheBestMoshe:thebestmoshe/allow-setting-all-56?expand=1) is what I have tried so far. However, it is not replacing the variables.

**Comment by krumware** [comment]
ok thanks for the diff! much easier to see it in action here. I'll see what I can debug

**Comment by TheBestMoshe** [comment]
I have this working on my [Home Assistant Add-on for Calendso](https://github.com/TheBestMoshe/home-assistant-addons/blob/cal.com-pinned-to-commit/cal.com/docker-entrypoint.sh)

If you want to see a working example, you can clone the repo and checkout the `cal.com-pinned-to-commit` branch. Then do the following steps:

Create a file in the `cal.com` directory `data/options.json` with the following content:
```
{
    "database_url": "postgresql://postgres:postgres@postgres:5432/cal?schema=public",
    "base_url": "http://localhost:3000",
    "jwt_secret": "secret",
    "calendso_encryption_key": "ejfoewurf939r3"
}
```

and run:
```
docker-compose build
docker-compose up
```

Prisma Studio will be accessible at `localhost:5555` so you can create a user. Calendso will be available at `localhost:3000`

To test the runtime variables were correctly set, go to the `/event-types` page and preview an event. If the event preview opens to the correct page, then the `base_url` in the config.json file is being set at runtime.

Note: The version of Calendso is pinned to an [older commit](https://github.com/calendso/calendso/tree/11e7779a585a0fcded5a02619332333a85d2cdc4), as I was unable to get it to build with newer commits as it had other errors.

**Comment by TheBestMoshe** [comment]
>ok thanks for the diff! much easier to see it in action here. I'll see what I can debug

The issue I was having was that it was not overwriting the dummy values. I think there is something wrong my _find and replace_ code in start.sh

**Comment by krumware** [comment]
Thanks @TheBestMoshe, will get to this as soon as I can

**Comment by krumware** [comment]
this was resolved
