### ISSUE TITLE
Use BASE_URL instead of example.com

### ISSUE THREAD

**Issue by Ak4zh** [calcom/docker#76]
Self hosted version uses https://calendso.example.com/ at many places.

- Click on preview Team url it opens https://calendso.example.com/team/xxxxxx
- The profile edit section where you set username also uses same example domain
- side panel on avatar popup
- Email edit section: To change your email, please contact help@cal.com
- Brand header in sidebar

All these can be replaced to use the BASE_URL env instead

**Comment by PeerRich** [comment]
i think this issue should be posted in https://github.com/calendso/calendso
