### ISSUE TITLE
Docker "Service 'calendso' failed to build" due to "Step 4/31 : COPY calendso/apps/web/prisma"

### ISSUE THREAD

**Issue by afroeagle** [calcom/docker#84]
**Environment**
1. Fresh install of Ubuntu 20.04.3 LTS Desktop

<br>

**Install Process**
1. Install `Docker` and `Docker-Compose` via the official Docker website procedure
2. Clone calendso-docker (I have also tried this with `--recursive` at the end as mentioned in https://github.com/calcom/docker/issues/12)
`git clone --recursive https://github.com/calendso/docker.git calendso-docker`
3. Change into the directory
`cd calendso-docker`
4. Rename .env.example to .env and update .env.
`cp .env.example .env`
5. Build and start calendso
`docker-compose up --build`

<br>

**Results**
```
$sudo docker-compose up --build
Creating network "calendso-docker_stack" with the default driver
Creating volume "calendso-docker_database-data" with default driver
Pulling database (postgres:)...
latest: Pulling from library/postgres
5eb5b503b376: Pull complete
daa0467a6c48: Pull complete
7cf625de49ef: Pull complete
bb8afcc973b2: Pull complete
c74bf40d29ee: Pull complete
2ceaf201bb22: Pull complete
1255f255c0eb: Pull complete
12a9879c7aa1: Pull complete
4e80271c8de8: Pull complete
04d0275af286: Pull complete
3d4fe3f39342: Pull complete
60f2aefbd6d9: Pull complete
98ace1022c39: Pull complete
Digest: sha256:156c50d4b6fe6ea4e4645ccdeabf54fedc59a561bfece047cdf4c26a42deab72
Status: Downloaded newer image for postgres:latest
Building calendso
Sending build context to Docker daemon   26.1MB
Step 1/31 : FROM node:14 as deps
14: Pulling from library/node
a834d7c95167: Pull complete 
57b3fa6f1b88: Pull complete 
778df3ecaa0f: Pull complete 
d353c340774e: Pull complete 
6370e0bc373d: Pull complete 
fb61153482cd: Pull complete 
78fb5822e501: Pull complete 
ba3577a691be: Pull complete 
bd38fd0dd57b: Pull complete 
Digest: sha256:b2c75df8c9706156c38b4f1f678d00e11cb2bfda09fc4ab6e36ec17ac9163865
Status: Downloaded newer image for node:14
 ---> 9cb3f042a684
Step 2/31 : WORKDIR /calcom
 ---> Running in 3cb224df2841
Removing intermediate container 3cb224df2841
 ---> 34be7496817b
Step 3/31 : COPY calendso/apps/web/package.json calendso/apps/web/yarn.lock ./
 ---> f22c2b1deaa7
Step 4/31 : COPY calendso/apps/web/prisma prisma
COPY failed: file not found in build context or excluded by .dockerignore: stat calendso/apps/web/prisma: file does not exist
ERROR: Service 'calendso' failed to build : Build failed
```

**Comment by nogara** [comment]
It seems as if https://github.com/calcom/cal.com/pull/1823 messed things up with the Prisma dir...

**Comment by afroeagle** [comment]
Any guidance on how to (at least temporarily) get past this obstacle? Thank you 😊

**Comment by AshnaSabu123** [comment]
Facing the same issue.

**Comment by apfelcast** [comment]
I solved this issue by 

`cp -r calendso/packages/prisma calendso/apps/web/`

and then re-run the build command

**Comment by krumware** [comment]
I'll take a look at this today. Sorry for the trouble, y'all. The main repo is in flux with the structure transition and we're having to react to them. Thanks for the help!

**Comment by searsaw** [comment]
This is related to a reorg of the main project. See [my comment here](https://github.com/calcom/docker/issues/85#issuecomment-1043339511)

**Comment by afroeagle** [comment]
> This is related to a reorg of the main project. See [my comment here](https://github.com/calcom/docker/issues/85#issuecomment-1043339511)

Thank you!!
