### ISSUE TITLE
 An unexpected error occurred: "https://registry.yarnpkg.com/@calcom%2flib: Not found".

### ISSUE THREAD

**Issue by AshnaSabu123** [calcom/docker#85]
I have done a fix my moving the prisma to another location but another issue occur.

 ---> Running in f6a7a687a701
yarn install v1.22.5
[1/5] Validating package.json...
[2/5] Resolving packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/@calcom%2flib: Not found".
info If you think this is a bug, please open a bug report with the information provided in "/calendso/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
ERROR: Service 'calendso' failed to build : The command '/bin/sh -c yarn install' returned a non-zero code: 1
❯

Please suggest the solution

**Comment by searsaw** [comment]
I'm working through some of these issues now. This is related to the fact that the main project moved to using Yarn workspaces. This is a pretty big reorg of the project and requires a good many changes to the Dockerfile. I'm trying to get these things fixed soon.

**Comment by afroeagle** [comment]
I am also experiencing this issue. Thank you for your efforts @searsaw!

**Comment by krumware** [comment]
please retest with latest, re: https://github.com/calcom/docker/pull/86
